# render.yaml
services:
  - type: web
    name: beanandhops-backend
    env: python
    region: singapore  # Choose closest region
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: postgres
    name: beanandhops-db
    region: singapore
    plan: free  # Or starter for production
    databaseName: beanandhops
    databaseUser: beanandhops
