# Generated by Django 5.2.5 on 2025-08-27 02:31

import beanandhops.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('rply_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rply_name', models.CharField(max_length=100)),
                ('rply_icon', models.ImageField(blank=True, null=True, upload_to=beanandhops.models.upload_to_profile)),
                ('rply_text', models.TextField(max_length=2000)),
                ('rply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('mnu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mnu_name', models.CharField(max_length=200)),
                ('mnu_image', models.ImageField(blank=True, null=True, upload_to=beanandhops.models.upload_to_menu)),
                ('mnu_description', models.TextField(max_length=500)),
                ('mnu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beanandhops.category')),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beanandhops.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('rvw_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rvw_icon', models.ImageField(blank=True, null=True, upload_to=beanandhops.models.upload_to_profile)),
                ('rvw_name', models.CharField(default='Anonymous', max_length=50)),
                ('rvw_rate', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rvw_text', models.TextField(blank=True, default=' ', max_length=2000, null=True)),
                ('rvw_image', models.ImageField(blank=True, null=True, upload_to=beanandhops.models.upload_to_review)),
                ('rvw_date', models.DateTimeField(auto_now_add=True)),
                ('rvw_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beanandhops.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='beanandhops.category')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='mnu_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beanandhops.subtype'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='mnu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beanandhops.type'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='beanandhops.type'),
        ),
    ]
