# Generated by Django 5.2.5 on 2025-08-27 07:18

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='mnu_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mnu_type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='beanandhops.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='mnu_subtype',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='mnu_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='beanandhops.subtype'),
        ),
    ]
