# Generated by Django 5.2.5 on 2025-08-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0002_alter_menuitem_mnu_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='rply_to_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beanandhops.reviews'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='rply_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
