# Generated by Django 5.2.5 on 2025-08-27 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0003_reply_rply_to_person_alter_reply_rply_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='mnu_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rvw_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rvw_rate',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
