# Generated by Django 5.2.5 on 2025-08-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0004_alter_menuitem_mnu_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prices',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnu_prices', to='beanandhops.menuitem'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='rply_to_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rvw_replies', to='beanandhops.reviews'),
        ),
    ]
