# Generated by Django 5.2.5 on 2025-09-01 03:06

import beanandhops.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0005_alter_prices_label_alter_prices_menu_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pst_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pst_image', models.ImageField(upload_to=beanandhops.models.upload_to_post)),
                ('pst_created_at', models.DateTimeField(auto_now_add=True)),
                ('pst_caption', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
