# Generated by Django 5.2.5 on 2025-09-01 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0006_post_alter_prices_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pst_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pst_menu', to='beanandhops.menuitem'),
        ),
    ]
