# Generated by Django 5.2.5 on 2025-09-18 04:18

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0007_post_pst_menu_item'),
        ('library', '0002_transfer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='mnu_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mnu_type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='library.category'),
        ),
        migrations.RemoveField(
            model_name='subtype',
            name='category',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='mnu_subtype',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='mnu_category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='library.subtype'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='mnu_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.type'),
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subtype',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
