# Generated by Django 5.2.5 on 2025-09-18 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beanandhops', '0010_reply_rply_user_reviews_rvw_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('like_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvw_likes', to='beanandhops.reviews')),
                ('like_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'unique_together': {('like_user', 'like_review')},
            },
        ),
    ]
